name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-17"



[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzIwZjU3NjktZmQ0Zi00MDM5LWIzNTktZDBlNGQ2ZjlkNmI2IiwidGVuYW50X2lkIjoiYTYxMjYzZTVmOWU4OTdkMmZkMjJmOWQyZTBiM2NlYjlhNzI2MDRhNzM0ZWZkN2FlYzlhOTUwYTM2YTg1ZmI5ZCIsImludGVybmFsX3NlY3JldCI6IjE1ZGRkMGI4LTEzZjAtNGEwZC05ZjliLTA1YzQ4Yzg4ODA5NCJ9.Yr-_x_V-GBbTLDwSoY-MPcnMrT86XxzkiS8M5JnWX0g"
JWT_SECRET = "MansiSecret"


#the database pick the url from here

# compatibility_flags = [ "nodejs_compat" ]

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1